# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20171101_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('', '\u65e0'), ('\u79d1\u5ba41', '\u79d1\u5ba41'), ('\u79d1\u5ba42', '\u79d1\u5ba42'), ('\u79d1\u5ba43', '\u79d1\u5ba43')], default='', max_length=20),
        ),
    ]
