# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20171109_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('0', ''), ('1', '\u6280\u672f\u5f00\u53d1\u79d1'), ('2', 'IT\u652f\u6491\u79d1'), ('3', '\u89c4\u5212\u53d1\u5c55\u79d1')], default='0', max_length=20),
        ),
    ]
