# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171028_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='scoreR1',
            field=models.IntegerField(default=0, verbose_name='\u884c\u4e3a\u89c4\u8303\u81ea\u8bc4\u5206'),
        ),
        migrations.AddField(
            model_name='report',
            name='scoreR2',
            field=models.IntegerField(default=0, verbose_name='\u884c\u4e3a\u89c4\u8303\u79d1\u8bc4\u5206'),
        ),
        migrations.AddField(
            model_name='report',
            name='scoreR3',
            field=models.IntegerField(default=0, verbose_name='\u884c\u4e3a\u89c4\u8303\u90e8\u8bc4\u5206'),
        ),
    ]
