# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20171101_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('0', '\u672a\u63d0\u4ea4'), ('1', '\u5df2\u63d0\u4ea4\u79d1\u5ba4'), ('2', '\u79d1\u5ba4\u5ba1\u6838\u4e2d'), ('3', '\u5df2\u63d0\u4ea4\u90e8\u95e8'), ('4', '\u90e8\u95e8\u5ba1\u6838\u4e2d'), ('5', '\u5df2\u5b58\u6863'), ('10', '\u9000\u56de'), ('20', '\u9000\u56de')], default='0', max_length=10),
        ),
    ]
