# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20171121_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='scoreD2',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='\u65e5\u5e38\u9879\u76ee\u79d1\u8bc4\u5206'),
        ),
        migrations.AlterField(
            model_name='report',
            name='scoreD3',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='\u65e5\u5e38\u9879\u76ee\u90e8\u8bc4\u5206'),
        ),
        migrations.AlterField(
            model_name='report',
            name='scoreL2',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='\u957f\u671f\u9879\u76ee\u79d1\u8bc4\u5206'),
        ),
        migrations.AlterField(
            model_name='report',
            name='scoreL3',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='\u957f\u671f\u9879\u76ee\u90e8\u8bc4\u5206'),
        ),
        migrations.AlterField(
            model_name='report',
            name='scoreR2',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='\u884c\u4e3a\u89c4\u8303\u79d1\u8bc4\u5206'),
        ),
        migrations.AlterField(
            model_name='report',
            name='scoreR3',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='\u884c\u4e3a\u89c4\u8303\u90e8\u8bc4\u5206'),
        ),
        migrations.AlterField(
            model_name='report',
            name='scoreS2',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='\u77ed\u671f\u9879\u76ee\u79d1\u8bc4\u5206'),
        ),
        migrations.AlterField(
            model_name='report',
            name='scoreS3',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='\u77ed\u671f\u9879\u76ee\u90e8\u8bc4\u5206'),
        ),
    ]
