# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20171121_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='note1',
            field=models.CharField(default='\u81ea\u8bc4\u5907\u6ce8', max_length=2048, verbose_name='\u81ea\u8bc4\u5907\u6ce8'),
        ),
        migrations.AddField(
            model_name='report',
            name='note2',
            field=models.CharField(default='\u79d1\u5ba4\u5907\u6ce8', max_length=2048, verbose_name='\u79d1\u5ba4\u5907\u6ce8'),
        ),
        migrations.AddField(
            model_name='report',
            name='note3',
            field=models.CharField(default='\u90e8\u95e8\u5907\u6ce8', max_length=2048, verbose_name='\u90e8\u95e8\u5907\u6ce8'),
        ),
    ]
