# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20171127_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='note1',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='\u52a0\u5206\u4e8b\u7531'),
        ),
        migrations.AlterField(
            model_name='report',
            name='note2',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='\u79d1\u5ba4\u6279\u590d'),
        ),
        migrations.AlterField(
            model_name='report',
            name='note3',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='\u90e8\u95e8\u6279\u590d'),
        ),
    ]
