# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-06 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20171117_1125'),
        ('main', '0013_auto_20171127_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoreL', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='\u957f\u671f\u9879\u76ee\u79d1\u8bc4\u5206')),
                ('scoreS', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='\u77ed\u671f\u9879\u76ee\u79d1\u8bc4\u5206')),
                ('scoreD', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='\u65e5\u5e38\u9879\u76ee\u79d1\u8bc4\u5206')),
                ('scoreR', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='\u884c\u4e3a\u89c4\u8303\u79d1\u8bc4\u5206')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraScore', to='accounts.Profile')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': '\u5176\u5b83\u79d1\u957f\u8bc4\u5206',
            },
        ),
        migrations.AddField(
            model_name='report',
            name='leader1Done',
            field=models.BooleanField(default=False, verbose_name='leader1\u5b8c\u6210'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('0', '\u672a\u63d0\u4ea4'), ('1', '\u5df2\u63d0\u4ea4\u79d1\u5ba4'), ('2', '\u79d1\u5ba4\u5ba1\u6838\u4e2d'), ('3', '\u5df2\u63d0\u4ea4\u90e8\u95e8'), ('4', '\u90e8\u95e8\u5ba1\u6838\u4e2d'), ('5', '\u5df2\u5b58\u6863'), ('6', '\u9000\u56de\u5458\u5de5'), ('7', '\u9000\u56de\u79d1\u5ba4'), ('8', '\u5176\u5b83\u79d1\u5ba4\u5ba1\u6838\u4e2d')], default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='extrascore',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraScore', to='main.Report'),
        ),
    ]
