# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-07 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20180206_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', '\u672a\u63d0\u4ea4'), ('2', '\u5ba1\u6838\u4e2d'), ('3', '\u5df2\u63d0\u4ea4\u90e8\u95e8'), ('4', '\u90e8\u95e8\u5ba1\u6838\u4e2d'), ('7', '\u9000\u56de\u79d1\u5ba4')], default='1', max_length=10)),
                ('leader', models.CharField(choices=[('1', '\u6280\u672f\u5f00\u53d1\u79d1'), ('2', 'IT\u652f\u6491\u79d1'), ('3', '\u89c4\u5212\u53d1\u5c55\u79d1')], max_length=20)),
                ('scoreL', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='\u957f\u671f\u9879\u76ee\u79d1\u8bc4\u5206')),
                ('scoreS', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='\u77ed\u671f\u9879\u76ee\u79d1\u8bc4\u5206')),
                ('scoreD', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='\u65e5\u5e38\u9879\u76ee\u79d1\u8bc4\u5206')),
                ('scoreR', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='\u884c\u4e3a\u89c4\u8303\u79d1\u8bc4\u5206')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': '\u62a5\u544a\u526f\u8868',
            },
        ),
        migrations.RemoveField(
            model_name='extrascore',
            name='leader',
        ),
        migrations.RemoveField(
            model_name='extrascore',
            name='report',
        ),
        migrations.RemoveField(
            model_name='report',
            name='leader1Done',
        ),
        migrations.DeleteModel(
            name='ExtraScore',
        ),
        migrations.AddField(
            model_name='extrareport',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraReports', to='main.Report'),
        ),
    ]
